version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    build:
      context: .
      dockerfile: ci.Dockerfile
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
      - DATABASE_MAX_CONNECTIONS=${DATABASE_MAX_CONNECTIONS}
      - DATABASE_SSL_ENABLED=${DATABASE_SSL_ENABLED}
      - DATABASE_REJECT_UNAUTHORIZED=${DATABASE_REJECT_UNAUTHORIZED}
      - NODE_ENV=${NODE_ENV}
      - APP_PORT=${APP_PORT}
      - APP_NAME=${APP_NAME}
      - API_PREFIX=${API_PREFIX}
      - APP_FALLBACK_LANGUAGE=${APP_FALLBACK_LANGUAGE}
      - APP_HEADER_LANGUAGE=${APP_HEADER_LANGUAGE}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
    ports:
      - ${APP_PORT}:${APP_PORT}
