version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    container_name: livechat_api
    build:
      context: .
      dockerfile: ci.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
